
spring:
  application:
    name: samsong_mall
  datasource:
    url: jdbc:mysql://localhost:3306/kd
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9001

mybatis-plus:
  configuration:
    #添加日志支持
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher